image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - deploy
       
before_script:
  - docker info

build:
  stage: build
  script:
    - docker-compose -f docker-compose.ci.yml build
        
test:
  stage: test
  script:
    - docker-compose -f docker-compose.ci.yml up -d
    - docker-compose -f docker-compose.ci.yml run web pytest tests/
    - docker-compose -f docker-compose.ci.yml down

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
